// Lista fechada de países + código de discagem (DDI), para o seletor de país do
// components/PhoneInput.tsx. Brasil é o primeiro item (padrão pré-selecionado em todo
// cadastro de telefone do produto — ver DESIGN-SYSTEM.md). Dado estático — nenhuma
// dependência nova.
export type Country = {
  iso: string; // ISO 3166-1 alpha-2
  nome: string;
  ddi: string; // só dígitos, sem "+"
};

export const COUNTRIES: Country[] = [
  { iso: "BR", nome: "Brasil", ddi: "55" },
  { iso: "US", nome: "Estados Unidos", ddi: "1" },
  { iso: "CA", nome: "Canadá", ddi: "1" },
  { iso: "AR", nome: "Argentina", ddi: "54" },
  { iso: "UY", nome: "Uruguai", ddi: "598" },
  { iso: "PY", nome: "Paraguai", ddi: "595" },
  { iso: "BO", nome: "Bolívia", ddi: "591" },
  { iso: "CL", nome: "Chile", ddi: "56" },
  { iso: "CO", nome: "Colômbia", ddi: "57" },
  { iso: "VE", nome: "Venezuela", ddi: "58" },
  { iso: "PE", nome: "Peru", ddi: "51" },
  { iso: "EC", nome: "Equador", ddi: "593" },
  { iso: "GY", nome: "Guiana", ddi: "592" },
  { iso: "SR", nome: "Suriname", ddi: "597" },
  { iso: "MX", nome: "México", ddi: "52" },
  { iso: "PA", nome: "Panamá", ddi: "507" },
  { iso: "CR", nome: "Costa Rica", ddi: "506" },
  { iso: "CU", nome: "Cuba", ddi: "53" },
  { iso: "DO", nome: "República Dominicana", ddi: "1" },
  { iso: "GT", nome: "Guatemala", ddi: "502" },
  { iso: "HN", nome: "Honduras", ddi: "504" },
  { iso: "NI", nome: "Nicarágua", ddi: "505" },
  { iso: "SV", nome: "El Salvador", ddi: "503" },
  { iso: "PT", nome: "Portugal", ddi: "351" },
  { iso: "ES", nome: "Espanha", ddi: "34" },
  { iso: "FR", nome: "França", ddi: "33" },
  { iso: "DE", nome: "Alemanha", ddi: "49" },
  { iso: "IT", nome: "Itália", ddi: "39" },
  { iso: "GB", nome: "Reino Unido", ddi: "44" },
  { iso: "IE", nome: "Irlanda", ddi: "353" },
  { iso: "NL", nome: "Países Baixos", ddi: "31" },
  { iso: "BE", nome: "Bélgica", ddi: "32" },
  { iso: "LU", nome: "Luxemburgo", ddi: "352" },
  { iso: "CH", nome: "Suíça", ddi: "41" },
  { iso: "AT", nome: "Áustria", ddi: "43" },
  { iso: "PL", nome: "Polônia", ddi: "48" },
  { iso: "SE", nome: "Suécia", ddi: "46" },
  { iso: "NO", nome: "Noruega", ddi: "47" },
  { iso: "DK", nome: "Dinamarca", ddi: "45" },
  { iso: "FI", nome: "Finlândia", ddi: "358" },
  { iso: "IS", nome: "Islândia", ddi: "354" },
  { iso: "GR", nome: "Grécia", ddi: "30" },
  { iso: "RU", nome: "Rússia", ddi: "7" },
  { iso: "UA", nome: "Ucrânia", ddi: "380" },
  { iso: "RO", nome: "Romênia", ddi: "40" },
  { iso: "HU", nome: "Hungria", ddi: "36" },
  { iso: "CZ", nome: "Tchéquia", ddi: "420" },
  { iso: "SK", nome: "Eslováquia", ddi: "421" },
  { iso: "HR", nome: "Croácia", ddi: "385" },
  { iso: "RS", nome: "Sérvia", ddi: "381" },
  { iso: "BG", nome: "Bulgária", ddi: "359" },
  { iso: "CY", nome: "Chipre", ddi: "357" },
  { iso: "MT", nome: "Malta", ddi: "356" },
  { iso: "AD", nome: "Andorra", ddi: "376" },
  { iso: "MC", nome: "Mônaco", ddi: "377" },
  { iso: "AO", nome: "Angola", ddi: "244" },
  { iso: "MZ", nome: "Moçambique", ddi: "258" },
  { iso: "CV", nome: "Cabo Verde", ddi: "238" },
  { iso: "GW", nome: "Guiné-Bissau", ddi: "245" },
  { iso: "ST", nome: "São Tomé e Príncipe", ddi: "239" },
  { iso: "TL", nome: "Timor-Leste", ddi: "670" },
  { iso: "ZA", nome: "África do Sul", ddi: "27" },
  { iso: "NG", nome: "Nigéria", ddi: "234" },
  { iso: "EG", nome: "Egito", ddi: "20" },
  { iso: "MA", nome: "Marrocos", ddi: "212" },
  { iso: "KE", nome: "Quênia", ddi: "254" },
  { iso: "GH", nome: "Gana", ddi: "233" },
  { iso: "SN", nome: "Senegal", ddi: "221" },
  { iso: "TZ", nome: "Tanzânia", ddi: "255" },
  { iso: "CN", nome: "China", ddi: "86" },
  { iso: "JP", nome: "Japão", ddi: "81" },
  { iso: "KR", nome: "Coreia do Sul", ddi: "82" },
  { iso: "IN", nome: "Índia", ddi: "91" },
  { iso: "ID", nome: "Indonésia", ddi: "62" },
  { iso: "TH", nome: "Tailândia", ddi: "66" },
  { iso: "VN", nome: "Vietnã", ddi: "84" },
  { iso: "PH", nome: "Filipinas", ddi: "63" },
  { iso: "MY", nome: "Malásia", ddi: "60" },
  { iso: "SG", nome: "Singapura", ddi: "65" },
  { iso: "HK", nome: "Hong Kong", ddi: "852" },
  { iso: "TW", nome: "Taiwan", ddi: "886" },
  { iso: "PK", nome: "Paquistão", ddi: "92" },
  { iso: "BD", nome: "Bangladesh", ddi: "880" },
  { iso: "IL", nome: "Israel", ddi: "972" },
  { iso: "TR", nome: "Turquia", ddi: "90" },
  { iso: "SA", nome: "Arábia Saudita", ddi: "966" },
  { iso: "AE", nome: "Emirados Árabes Unidos", ddi: "971" },
  { iso: "QA", nome: "Catar", ddi: "974" },
  { iso: "KW", nome: "Kuwait", ddi: "965" },
  { iso: "IR", nome: "Irã", ddi: "98" },
  { iso: "IQ", nome: "Iraque", ddi: "964" },
  { iso: "JO", nome: "Jordânia", ddi: "962" },
  { iso: "LB", nome: "Líbano", ddi: "961" },
  { iso: "AU", nome: "Austrália", ddi: "61" },
  { iso: "NZ", nome: "Nova Zelândia", ddi: "64" },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // Brasil

export function findCountryByDdi(ddi: string): Country | undefined {
  const digits = ddi.replace(/\D/g, "");
  return COUNTRIES.find((c) => c.ddi === digits);
}
